Repository BOMWhatsUp/rental_market_frontend, pull requests merged in 2023-03, with the labels that each got.

#9 Feature/login
  src/assets/google.svg
  src/assets/kakao.svg
  src/pages/LoginPage.tsx
  tailwind.config.cjs
Labels: style

#14 feat: 회원가입 정규식 추가
  src/pages/SignUpPage.tsx
Labels: style, feature

#15 feat: 중복 체크 및 결과 문구 추가
  src/pages/SignUpPage.tsx
Labels: style, feature

#16 Feature/product ui2
  src/components/RentalProductItem.tsx
  src/pages/MainPage.tsx
  src/pages/RentalCreatePage.tsx
  src/pages/RentalDetailPage.tsx
Labels: style, feature

#17 Feature/chat UI
  package-lock.json
  package.json
  src/components/ChatListItem.tsx
  src/pages/ChatDetailPage.tsx
  src/pages/ChatListPage.tsx
  tailwind.config.cjs
Labels: style

#21 Feature/myproducts UI
  src/components/RentalProductItem.tsx
  src/pages/MyRentalPage.tsx
  src/pages/RentalDetailPage.tsx
Labels: style

#24 페이지 UI - 채팅목록, 채팅방, 랜탈 구매 페이지
  src/pages/ChatDetailPage.tsx
  src/pages/ChatListPage.tsx
  src/pages/RentalPayPage.tsx
Labels: style

#27 style: 렌탈 반납 페이지 ui
  src/pages/RentalReturnPage.tsx
Labels: style

#29 config: MSW, react-query, recoil 설치 및 테스트
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/Test.tsx
  src/main.tsx
  src/mocks/browsers.js
  src/mocks/handlers.js
  tsconfig.json
Labels: feature

#33 feat: 회원가입 기능 테스트, 스타일 수정
  src/api/signUp/signUpAPI.ts
  src/hooks/useSignUp.ts
  src/mocks/handlers.js
  src/pages/SignUpPage.tsx
Labels: style, feature

#32 feat: CreateRental 페이지 POST 목업 테스트
  src/Test.tsx
  src/api/rentalCreate.ts
  src/hooks/useProduct.ts
  src/mocks/handlers.js
  src/pages/RentalCreatePage.tsx
Labels: feature

#34 product post 요청, 주소 입력 api 적용
  package-lock.json
  package.json
  src/api/rentalCreate.ts
  src/components/DaumAddressButton.tsx
  src/hooks/useProduct.ts
  src/mocks/handlers.js
  src/pages/RentalCreatePage.tsx
  src/types/product.ts
Labels: feature

#40 Feature/login
  package-lock.json
  package.json
  src/App.tsx
  src/api/login/loginAPI.ts
  src/atoms/token.ts
  src/atoms/userInfo.ts
  src/components/Layout.tsx
  src/hooks/useLogin.ts
  src/main.tsx
  src/mocks/handlers.js
  src/pages/LoginPage.tsx
  tsconfig.json
Labels: style, feature

#41 Feature/get rentals
  package-lock.json
  package.json
  src/App.tsx
  src/api/fetch.ts
  src/atoms/currentPageAtom.ts
  src/components/ProductList.tsx
  src/components/RentalProductItem.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useProduct.ts
  src/mocks/handlers.js
  src/pages/MainPage.tsx
  src/pages/RentalCreatePage.tsx
  src/pages/ScrollTest.tsx
  src/types/product.ts
Labels: feature

#43 :sparkles: feat: chat test 진행중...
  package-lock.json
  package.json
  src/App.tsx
  src/pages/ChatListTest.tsx
  src/pages/ChatTest.tsx
  src/pages/NotFound.tsx
  tsconfig.json
  vite.config.ts
Labels: feature

#44 product 관련 기능들 및 테스트
  package-lock.json
  package.json
  src/App.tsx
  src/api/axiosInstance.ts
  src/api/fetch.ts
  src/api/rentalCreate.ts
  src/api/rentalProduct/rentalProductAPI.ts
  src/assets/404sample.png
  src/assets/profile_sample.png
  src/components/Badge.tsx
  src/components/DaumAddressButton.tsx
  src/components/ProductList.tsx
  src/components/RentalProductItem.tsx
  src/hooks/useProduct.ts
  src/mocks/handlers.js
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/MyRentalPage.tsx
  src/pages/RentalCreatePage.tsx
  src/pages/RentalDetailPage.tsx
  src/pages/RentalPayPage.tsx
  src/pages/ScrollTest.tsx
  src/types/product.ts
  src/utils/converter.ts
Labels: help wanted, style, feature

#54 Feature/chat
  package-lock.json
  package.json
  src/App.tsx
  src/api/login/loginAPI.ts
  src/api/signUp/signUpAPI.ts
  src/components/ChatListItem.tsx
  src/components/ChatMessage.tsx
  src/components/Layout.tsx
  src/components/RentalProductItem.tsx
  src/mocks/handlers.js
  src/pages/Chat.tsx
  src/pages/ChatDetailPage.tsx
  src/pages/ChatList.tsx
  src/pages/ChatListPage.tsx
  src/pages/ChatTest.tsx
  src/pages/LoginPage.tsx
  src/pages/RentalDetailTestPage.tsx
  src/pages/RentalPayPage.tsx
Labels: style, feature
