Repository BOMWhatsUp/rental_market_frontend, pull requests merged in 2023-04, with the labels that each got.

#57 :rocket: test: vercel환경 테스트중1
  src/api/rentalProduct/rentalProductAPI.ts
Labels: test

#58 :rocket: test:SSL인증서 없이 http 요청 허용 위한 시도-vercel.config수정
  vercel.json
Labels: test

#59 :rocket: test: has 속성 관련 요청 이상하게 가는 문제 생겨서 config수정
  vercel.json
Labels: test

#60 :rocket: test: http 유효성 검증 생략하도록 axios 요청 설정 시도
  src/api/axiosInstance.ts
Labels: test

#61 :rocket: test:https to http 결국 오류만 커져서 테스트 전 상태로 되돌림
  src/api/axiosInstance.ts
  vercel.json
Labels: test

#62 :wrench: test: http 에러 해결을 위해 vite.config 수정
  vite.config.ts
Labels: test

#67 Feature/chat
  package-lock.json
  package.json
  src/App.tsx
  src/api/login/loginAPI.ts
  src/api/signUp/signUpAPI.ts
  src/components/ChatListItem.tsx
  src/components/Layout.tsx
  src/hooks/useSignUp.ts
  src/pages/ChatListPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignUpPage.tsx
Labels: style, feature, test

#69 product 관련 및 공통요소 수정, 백엔드 연동 테스트
  src/App.tsx
  src/api/axiosInstance.ts
  src/api/rentalProduct/rentalProductAPI.ts
  src/assets/logo_sm.png
  src/components/DaumAddressButton.tsx
  src/components/Layout.tsx
  src/hooks/useProduct.ts
  src/pages/MainPage.tsx
  src/pages/MyRentalHistoryPage.tsx
  src/pages/RentalCreatePage.tsx
  src/pages/RentalDetailPage.tsx
  src/pages/RentalPayPage.tsx
  src/types/product.ts
Labels: enhancement, feature

#71 채팅 및 프로덕트 연동작업 과 세부 기능 개발, 서버연동 테스트
  src/App.tsx
  src/api/chat/chatAPI.ts
  src/api/login/loginAPI.ts
  src/api/rentalProduct/rentalProductAPI.ts
  src/api/signUp/signUpAPI.ts
  src/components/ChatListItem.tsx
  src/components/ChatMessage.tsx
  src/components/ProductList.tsx
  src/components/RentalProductHistoryItem.tsx
  src/components/RentalProductItem.tsx
  src/pages/Chat.tsx
  src/pages/ChatListPage.tsx
  src/pages/MainPage copy.tsx
  src/pages/MainPage.tsx
  src/pages/MyRentalHistoryPage.tsx
  src/pages/RentalDetailPage copy.tsx
  src/pages/RentalDetailPage.tsx
  src/pages/RentalPayPage.tsx
  src/pages/RentalReturnPage.tsx
Labels: enhancement, feature

#72 :sparkles: feat: category 에러 해결 및 간단한 검토로직
  src/pages/RentalCreatePage.tsx
Labels: enhancement, feature

#75 Feature/chat product return and pay
  src/api/login/loginAPI.ts
  src/api/rentalProduct/rentalProductAPI.ts
  src/api/signUp/signUpAPI.ts
  src/components/ChatListItem.tsx
  src/main.tsx
  src/pages/Chat.tsx
  src/pages/ChatListPage.tsx
  src/pages/RentalDetailPage.tsx
  src/pages/RentalPayPage.tsx
  src/pages/RentalReturnPage.tsx
Labels: style, feature
